### ISSUE TITLE
[FR] Add support for use of Anthropic models

### ISSUE THREAD

**Issue by maxthraxx** [0n4li/collab-ai#1]
As title says. OAI and Anthropic models are the top dogs in the closed AI space, it would be cool to have debates with different OAI vs. Anthropic models.

**Comment by 0n4li** [comment]
There is no restriction on any model.

You can use anthropic models like this:

```bash
python run_debate_model.py --question "How many 'r's are there in strawberry?" --user_instructions "Break all the letters, index only the 'r's and return the count" -c "r-in-strawberry" -m1 openai/gpt-4o-mini -m2 anthropic/claude-3.5-haiku
```

You can use any model by setting `-m1` and `-m2` parameters.

**Comment by 0n4li** [comment]
Closing the issue
